---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  namespace: env-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        env1: dev
        app: tomcat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: tomcat
        image: snaidu/rideeasy:22
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
