---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: env-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        env1: dev
        app: tomcat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: tomcat
        image: snaidu/rideeasy:*
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
