---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  namespace: env-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        env1: dev
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: {$IMAGE}
        ports:
          - containerPort: 8080
            protocol: TCP