---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: env-dev
spec:
  selector:
    env1: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
  type: LoadBalancer